configuration: Release  

# Install required Python packages before running the script  
before_build:  
  - pip install telebot pymongo aiohttp flask python-telegram-bot  

# Grant execute permissions  
build:  
  verbosity: minimal  
  script:  
    - chmod +x *  

# Run the Python script  
test_script:  
  - python golem.py
